services:
  - type: web
    name: open-webui
    env: docker
    dockerfilePath: ./Dockerfile
    scaling:
      minInstances: 1
      maxInstances: 2
      targetCPUPercent: 70
    envVars:
      - key: PORT
        value: 8080
      - key: OPENAI_API_BASE_URL
        value: https://api.heroku.com/inference
      - key: OPENAI_API_KEY
        sync: false
      - key: WEBUI_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: open-webui-db
          property: connectionString
    healthCheckPath: /health

databases:
  - name: open-webui-db
    databaseName: openwebui
    user: openwebui
